version: '3.1'

services:

  web:
    build: .
    volumes:
    - .:/app
    ports:
    - "5000:5000"
    depends_on:
    - db

  db:
    ports:
    - "5432:5432"
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass